# Generated by Django 5.2.15 on 2026-06-19 13:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('language', models.CharField(default='en', max_length=10)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('suggested_by_ai', 'Suggested by AI'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pieces', to='campaigns.campaign')),
                ('original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='content.contentpiece')),
            ],
            options={
                'db_table': 'content_pieces',
                'indexes': [models.Index(fields=['campaign'], name='content_pie_campaig_895127_idx'), models.Index(fields=['state'], name='content_pie_state_5840fc_idx'), models.Index(fields=['is_deleted'], name='content_pie_is_dele_704988_idx')],
            },
        ),
    ]
