# Generated by Django 5.2.15 on 2026-06-19 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contentpiece',
            name='content_pie_campaig_895127_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentpiece',
            name='content_pie_state_5840fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='contentpiece',
            name='content_pie_is_dele_704988_idx',
        ),
        migrations.AddField(
            model_name='contentpiece',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='contentpiece',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_pieces', to='campaigns.campaign'),
        ),
        migrations.AddIndex(
            model_name='contentpiece',
            index=models.Index(fields=['campaign', 'is_deleted', '-created_at'], name='idx_content_campaign_list'),
        ),
        migrations.AddIndex(
            model_name='contentpiece',
            index=models.Index(fields=['is_deleted', '-created_at'], name='idx_content_deleted_created'),
        ),
        migrations.AddIndex(
            model_name='contentpiece',
            index=models.Index(fields=['campaign', 'state'], name='idx_content_campaign_state'),
        ),
    ]
