# Generated by Django 5.2.15 on 2026-06-19 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_remove_contentpiece_content_pie_campaig_895127_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=30)),
                ('feedback', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='content.contentpiece')),
            ],
            options={
                'db_table': 'state_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_piece', '-created_at'], name='idx_history_content_created')],
            },
        ),
    ]
