# Generated by Django 5.2.15 on 2026-06-22 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_contentpiece_content_pie_campaig_895127_idx_and_more'),
        ('reviews', '0001_add_state_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statehistory',
            name='content_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_history', to='content.contentpiece'),
        ),
        migrations.AlterField(
            model_name='statehistory',
            name='feedback',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
